spring:
  boot:
    admin:
      context-path: admin-service
  application:
    name: discovery-service
server:
  port: 8081
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka/

logging:
  level:
    com:
      stc: INFO
    springFramework:
      web:
        client:
          RestTemplate: INFO
  file:
    name: logs/discovery.log